import { IconFamily } from "@/components/dynamic-icon";

export interface FoodIcon {
  name: string;
  family: IconFamily;
  label?: string;
}

export const FOOD_ICONS: FoodIcon[] = [
  // Existing items
  { name: "cheese", family: "MaterialCommunityIcons" },
  { name: "egg", family: "MaterialCommunityIcons" },
  { name: "egg-fried", family: "MaterialCommunityIcons" },
  { name: "cow", family: "MaterialCommunityIcons" },
  { name: "food-apple", family: "MaterialCommunityIcons" },
  { name: "carrot", family: "MaterialCommunityIcons" },
  { name: "leaf", family: "MaterialCommunityIcons" },
  { name: "fruit-grapes", family: "MaterialCommunityIcons" },
  { name: "corn", family: "MaterialCommunityIcons" },
  { name: "food-drumstick", family: "MaterialCommunityIcons" },
  { name: "food-steak", family: "MaterialCommunityIcons" },
  { name: "fish", family: "MaterialCommunityIcons" },
  { name: "sausage", family: "MaterialCommunityIcons" },
  { name: "bread-slice", family: "MaterialCommunityIcons" },
  { name: "cake", family: "MaterialCommunityIcons" },
  { name: "cookie", family: "MaterialCommunityIcons" },
  { name: "cupcake", family: "MaterialCommunityIcons" },
  { name: "baguette", family: "MaterialCommunityIcons" },
  { name: "snowflake", family: "MaterialCommunityIcons" },
  { name: "ice-cream", family: "MaterialCommunityIcons" },
  { name: "fridge", family: "MaterialCommunityIcons" },
  { name: "food-variant", family: "MaterialCommunityIcons" },
  { name: "pot", family: "MaterialCommunityIcons" },
  { name: "bowl-mix", family: "MaterialCommunityIcons" },
  { name: "coffee", family: "MaterialCommunityIcons" },
  { name: "beer", family: "MaterialCommunityIcons" },
  { name: "cup", family: "MaterialCommunityIcons" },
  { name: "glass-cocktail", family: "MaterialCommunityIcons" },
  { name: "water", family: "MaterialCommunityIcons" },
  { name: "popcorn", family: "MaterialCommunityIcons" },
  { name: "candy", family: "MaterialCommunityIcons" },
  { name: "peanut", family: "MaterialCommunityIcons" },
  { name: "food-croissant", family: "MaterialCommunityIcons" },
  { name: "pasta", family: "MaterialCommunityIcons" },
  { name: "shaker", family: "MaterialCommunityIcons" },
  { name: "basket", family: "MaterialCommunityIcons" },
  { name: "chili-mild", family: "MaterialCommunityIcons" },
  { name: "sprout", family: "MaterialCommunityIcons" },
  { name: "condiment", family: "MaterialCommunityIcons" },
  { name: "bottle-wine", family: "MaterialCommunityIcons" },
  { name: "pizza", family: "MaterialCommunityIcons" },
  { name: "hamburger", family: "MaterialCommunityIcons" },
  { name: "food-hot-dog", family: "MaterialCommunityIcons" },
  { name: "taco", family: "MaterialCommunityIcons" },
  { name: "noodles", family: "MaterialCommunityIcons" },
  { name: "rice", family: "MaterialCommunityIcons" },
  { name: "food-turkey", family: "MaterialCommunityIcons" },
  { name: "food-takeout-box", family: "MaterialCommunityIcons" },
  { name: "nutrition", family: "MaterialCommunityIcons" },
  { name: "baby-bottle", family: "MaterialCommunityIcons" },
  { name: "paw", family: "MaterialCommunityIcons" },
  { name: "soup-kitchen", family: "MaterialIcons" },
  { name: "barley", family: "MaterialCommunityIcons" },
  { name: "health-and-safety", family: "MaterialIcons" },
  { name: "spray-bottle", family: "MaterialCommunityIcons" },
  { name: "baby-carriage", family: "MaterialCommunityIcons" },
  { name: "dog", family: "MaterialCommunityIcons" },
  { name: "cat", family: "MaterialCommunityIcons" },
  { name: "shapes", family: "FontAwesome5" },
  { name: "bacon", family: "FontAwesome5" },
  { name: "emoji-food-beverage", family: "MaterialIcons" },

  // Additional MaterialCommunityIcons - Fruits & Vegetables
  { name: "fruit-cherries", family: "MaterialCommunityIcons" },
  { name: "fruit-citrus", family: "MaterialCommunityIcons" },
  { name: "fruit-pineapple", family: "MaterialCommunityIcons" },
  { name: "fruit-watermelon", family: "MaterialCommunityIcons" },
  { name: "mushroom", family: "MaterialCommunityIcons" },
  { name: "pumpkin", family: "MaterialCommunityIcons" },
  { name: "chili-hot", family: "MaterialCommunityIcons" },
  { name: "chili-medium", family: "MaterialCommunityIcons" },
  { name: "chili-off", family: "MaterialCommunityIcons" },
  { name: "seed", family: "MaterialCommunityIcons" },
  { name: "seed-outline", family: "MaterialCommunityIcons" },
  { name: "olive", family: "MaterialCommunityIcons" },

  // Additional MaterialCommunityIcons - Proteins & Meats
  { name: "ham", family: "MaterialCommunityIcons" },
  { name: "pig", family: "MaterialCommunityIcons" },
  { name: "pig-variant", family: "MaterialCommunityIcons" },
  { name: "shrimp", family: "MaterialCommunityIcons" },
  { name: "egg-outline", family: "MaterialCommunityIcons" },
  { name: "egg-off", family: "MaterialCommunityIcons" },
  { name: "egg-off-outline", family: "MaterialCommunityIcons" },

  // Additional MaterialCommunityIcons - Baked Goods & Sweets
  { name: "muffin", family: "MaterialCommunityIcons" },
  { name: "pretzel", family: "MaterialCommunityIcons" },
  { name: "cake-variant", family: "MaterialCommunityIcons" },
  { name: "cake-layered", family: "MaterialCommunityIcons" },
  { name: "cookie-outline", family: "MaterialCommunityIcons" },
  { name: "candy-outline", family: "MaterialCommunityIcons" },
  { name: "candy-off", family: "MaterialCommunityIcons" },
  { name: "candy-off-outline", family: "MaterialCommunityIcons" },
  { name: "ice-pop", family: "MaterialCommunityIcons" },
  { name: "chocolate", family: "MaterialCommunityIcons" },

  // Additional MaterialCommunityIcons - Grains & Staples
  { name: "wheat", family: "MaterialCommunityIcons" },
  { name: "grain", family: "MaterialCommunityIcons" },
  { name: "bread-slice-outline", family: "MaterialCommunityIcons" },

  // Additional MaterialCommunityIcons - Condiments & Sauces
  { name: "sauce", family: "MaterialCommunityIcons" },
  { name: "soy-sauce", family: "MaterialCommunityIcons" },
  { name: "mustard", family: "MaterialCommunityIcons" },
  { name: "shaker-outline", family: "MaterialCommunityIcons" },

  // Additional MaterialCommunityIcons - Beverages
  { name: "tea", family: "MaterialCommunityIcons" },
  { name: "tea-outline", family: "MaterialCommunityIcons" },
  { name: "coffee-outline", family: "MaterialCommunityIcons" },
  { name: "coffee-to-go", family: "MaterialCommunityIcons" },
  { name: "coffee-to-go-outline", family: "MaterialCommunityIcons" },
  { name: "cup-outline", family: "MaterialCommunityIcons" },
  { name: "cup-water", family: "MaterialCommunityIcons" },
  { name: "cup-off", family: "MaterialCommunityIcons" },
  { name: "cup-off-outline", family: "MaterialCommunityIcons" },
  { name: "mug", family: "MaterialCommunityIcons" },
  { name: "mug-outline", family: "MaterialCommunityIcons" },
  { name: "glass-wine", family: "MaterialCommunityIcons" },
  { name: "glass-tulip", family: "MaterialCommunityIcons" },
  { name: "glass-flute", family: "MaterialCommunityIcons" },
  { name: "glass-mug", family: "MaterialCommunityIcons" },
  { name: "glass-mug-variant", family: "MaterialCommunityIcons" },
  { name: "glass-pint-outline", family: "MaterialCommunityIcons" },
  { name: "glass-stange", family: "MaterialCommunityIcons" },
  { name: "bottle-soda", family: "MaterialCommunityIcons" },
  { name: "bottle-soda-outline", family: "MaterialCommunityIcons" },
  { name: "bottle-soda-classic", family: "MaterialCommunityIcons" },
  { name: "bottle-soda-classic-outline", family: "MaterialCommunityIcons" },
  { name: "bottle-wine-outline", family: "MaterialCommunityIcons" },
  { name: "bottle-tonic", family: "MaterialCommunityIcons" },
  { name: "bottle-tonic-outline", family: "MaterialCommunityIcons" },
  { name: "liquor", family: "MaterialCommunityIcons" },
  { name: "beer-outline", family: "MaterialCommunityIcons" },
  { name: "hops", family: "MaterialCommunityIcons" },

  // Additional MaterialCommunityIcons - Kitchen Appliances
  { name: "fridge-outline", family: "MaterialCommunityIcons" },
  { name: "fridge-industrial", family: "MaterialCommunityIcons" },
  { name: "fridge-industrial-outline", family: "MaterialCommunityIcons" },
  { name: "stove", family: "MaterialCommunityIcons" },
  { name: "microwave", family: "MaterialCommunityIcons" },
  { name: "toaster", family: "MaterialCommunityIcons" },
  { name: "toaster-oven", family: "MaterialCommunityIcons" },
  { name: "toaster-off", family: "MaterialCommunityIcons" },
  { name: "blender", family: "MaterialCommunityIcons" },
  { name: "blender-outline", family: "MaterialCommunityIcons" },
  { name: "coffee-maker", family: "MaterialCommunityIcons" },
  { name: "coffee-maker-outline", family: "MaterialCommunityIcons" },
  { name: "kettle", family: "MaterialCommunityIcons" },
  { name: "kettle-outline", family: "MaterialCommunityIcons" },
  { name: "kettle-steam", family: "MaterialCommunityIcons" },
  { name: "kettle-steam-outline", family: "MaterialCommunityIcons" },
  { name: "dishwasher", family: "MaterialCommunityIcons" },
  { name: "dishwasher-alert", family: "MaterialCommunityIcons" },
  { name: "dishwasher-off", family: "MaterialCommunityIcons" },

  // Additional MaterialCommunityIcons - Cookware & Utensils
  { name: "pot-outline", family: "MaterialCommunityIcons" },
  { name: "pot-steam", family: "MaterialCommunityIcons" },
  { name: "pot-steam-outline", family: "MaterialCommunityIcons" },
  { name: "pot-mix", family: "MaterialCommunityIcons" },
  { name: "pot-mix-outline", family: "MaterialCommunityIcons" },
  { name: "bowl", family: "MaterialCommunityIcons" },
  { name: "bowl-outline", family: "MaterialCommunityIcons" },
  { name: "bowl-mix-outline", family: "MaterialCommunityIcons" },
  { name: "silverware", family: "MaterialCommunityIcons" },
  { name: "silverware-fork", family: "MaterialCommunityIcons" },
  { name: "silverware-fork-knife", family: "MaterialCommunityIcons" },
  { name: "silverware-spoon", family: "MaterialCommunityIcons" },
  { name: "silverware-variant", family: "MaterialCommunityIcons" },
  { name: "silverware-clean", family: "MaterialCommunityIcons" },
  { name: "knife", family: "MaterialCommunityIcons" },
  { name: "grill", family: "MaterialCommunityIcons" },
  { name: "grill-outline", family: "MaterialCommunityIcons" },

  // Additional MaterialCommunityIcons - Food Related
  { name: "food-fork-drink", family: "MaterialCommunityIcons" },
  { name: "food-off", family: "MaterialCommunityIcons" },
  { name: "food-off-outline", family: "MaterialCommunityIcons" },
  { name: "food-apple-outline", family: "MaterialCommunityIcons" },
  { name: "food-halal", family: "MaterialCommunityIcons" },
  { name: "food-kosher", family: "MaterialCommunityIcons" },
  { name: "food-variant-off", family: "MaterialCommunityIcons" },

  // Additional MaterialCommunityIcons - Cooking & Measurement
  { name: "scale", family: "MaterialCommunityIcons" },
  { name: "scale-balance", family: "MaterialCommunityIcons" },
  { name: "timer", family: "MaterialCommunityIcons" },
  { name: "timer-outline", family: "MaterialCommunityIcons" },
  { name: "timer-sand", family: "MaterialCommunityIcons" },
  { name: "thermometer", family: "MaterialCommunityIcons" },
  { name: "thermometer-lines", family: "MaterialCommunityIcons" },
  { name: "fire", family: "MaterialCommunityIcons" },
  { name: "campfire", family: "MaterialCommunityIcons" },

  // Additional MaterialCommunityIcons - Shopping & Storage
  { name: "basket-outline", family: "MaterialCommunityIcons" },
  { name: "basket-fill", family: "MaterialCommunityIcons" },
  { name: "cart", family: "MaterialCommunityIcons" },
  { name: "cart-outline", family: "MaterialCommunityIcons" },
  { name: "store", family: "MaterialCommunityIcons" },
  { name: "storefront", family: "MaterialCommunityIcons" },
  { name: "storefront-outline", family: "MaterialCommunityIcons" },
  { name: "receipt", family: "MaterialCommunityIcons" },
  { name: "cash-register", family: "MaterialCommunityIcons" },
  { name: "jar", family: "MaterialCommunityIcons" },
  { name: "jar-outline", family: "MaterialCommunityIcons" },

  // Additional MaterialCommunityIcons - Herbs & Nature
  { name: "leaf-maple", family: "MaterialCommunityIcons" },
  { name: "leaf-circle", family: "MaterialCommunityIcons" },
  { name: "leaf-circle-outline", family: "MaterialCommunityIcons" },
  { name: "sprout-outline", family: "MaterialCommunityIcons" },
  { name: "flower", family: "MaterialCommunityIcons" },
  { name: "flower-outline", family: "MaterialCommunityIcons" },
  { name: "bee", family: "MaterialCommunityIcons" },
  { name: "beehive-outline", family: "MaterialCommunityIcons" },

  // Additional MaterialCommunityIcons - Misc Food
  { name: "french-fries", family: "MaterialCommunityIcons" },
  { name: "sushi", family: "MaterialCommunityIcons" },
  { name: "burrito", family: "MaterialCommunityIcons" },

  // FontAwesome5 additions
  { name: "pepper-hot", family: "FontAwesome5" },
  { name: "cookie-bite", family: "FontAwesome5" },
  { name: "pizza-slice", family: "FontAwesome5" },
  { name: "hamburger", family: "FontAwesome5" },
  { name: "hotdog", family: "FontAwesome5" },
  { name: "ice-cream", family: "FontAwesome5" },
  { name: "lemon", family: "FontAwesome5" },
  { name: "apple-alt", family: "FontAwesome5" },
  { name: "carrot", family: "FontAwesome5" },
  { name: "egg", family: "FontAwesome5" },
  { name: "fish", family: "FontAwesome5" },
  { name: "drumstick-bite", family: "FontAwesome5" },
  { name: "birthday-cake", family: "FontAwesome5" },
  { name: "candy-cane", family: "FontAwesome5" },
  { name: "wine-bottle", family: "FontAwesome5" },
  { name: "wine-glass", family: "FontAwesome5" },
  { name: "wine-glass-alt", family: "FontAwesome5" },
  { name: "beer", family: "FontAwesome5" },
  { name: "cocktail", family: "FontAwesome5" },
  { name: "coffee", family: "FontAwesome5" },
  { name: "mug-hot", family: "FontAwesome5" },
  { name: "glass-martini", family: "FontAwesome5" },
  { name: "glass-martini-alt", family: "FontAwesome5" },
  { name: "glass-whiskey", family: "FontAwesome5" },
  { name: "glass-cheers", family: "FontAwesome5" },
  { name: "blender", family: "FontAwesome5" },
  { name: "utensils", family: "FontAwesome5" },
  { name: "utensil-spoon", family: "FontAwesome5" },
  { name: "mortar-pestle", family: "FontAwesome5" },
  { name: "weight", family: "FontAwesome5" },
  { name: "balance-scale", family: "FontAwesome5" },
  { name: "balance-scale-left", family: "FontAwesome5" },
  { name: "balance-scale-right", family: "FontAwesome5" },
  { name: "shopping-basket", family: "FontAwesome5" },
  { name: "shopping-cart", family: "FontAwesome5" },
  { name: "store", family: "FontAwesome5" },
  { name: "store-alt", family: "FontAwesome5" },
  { name: "seedling", family: "FontAwesome5" },
  { name: "leaf", family: "FontAwesome5" },
  { name: "fire", family: "FontAwesome5" },
  { name: "fire-alt", family: "FontAwesome5" },
  { name: "thermometer-half", family: "FontAwesome5" },
  { name: "stroopwafel", family: "FontAwesome5" },
  { name: "bread-slice", family: "FontAwesome5" },
  { name: "cheese", family: "FontAwesome5" },

  // Ionicons additions
  { name: "cafe", family: "Ionicons" },
  { name: "cafe-outline", family: "Ionicons" },
  { name: "beer-outline", family: "Ionicons" },
  { name: "wine", family: "Ionicons" },
  { name: "wine-outline", family: "Ionicons" },
  { name: "pizza", family: "Ionicons" },
  { name: "pizza-outline", family: "Ionicons" },
  { name: "fast-food", family: "Ionicons" },
  { name: "fast-food-outline", family: "Ionicons" },
  { name: "fish-outline", family: "Ionicons" },
  { name: "nutrition-outline", family: "Ionicons" },
  { name: "ice-cream-outline", family: "Ionicons" },
  { name: "leaf-outline", family: "Ionicons" },
  { name: "water-outline", family: "Ionicons" },
  { name: "flame", family: "Ionicons" },
  { name: "flame-outline", family: "Ionicons" },
  { name: "snow-outline", family: "Ionicons" },
  { name: "basket-outline", family: "Ionicons" },
  { name: "cart", family: "Ionicons" },
  { name: "cart-outline", family: "Ionicons" },
  { name: "storefront-outline", family: "Ionicons" },
  { name: "receipt-outline", family: "Ionicons" },
  { name: "restaurant", family: "Ionicons" },
  { name: "restaurant-outline", family: "Ionicons" },
  { name: "egg", family: "Ionicons" },
  { name: "egg-outline", family: "Ionicons" },

  // MaterialIcons additions
  { name: "restaurant", family: "MaterialIcons" },
  { name: "restaurant-menu", family: "MaterialIcons" },
  { name: "local-cafe", family: "MaterialIcons" },
  { name: "local-bar", family: "MaterialIcons" },
  { name: "local-pizza", family: "MaterialIcons" },
  { name: "local-dining", family: "MaterialIcons" },
  { name: "local-grocery-store", family: "MaterialIcons" },
  { name: "kitchen", family: "MaterialIcons" },
  { name: "microwave", family: "MaterialIcons" },
  { name: "blender", family: "MaterialIcons" },
  { name: "rice-bowl", family: "MaterialIcons" },
  { name: "ramen-dining", family: "MaterialIcons" },
  { name: "bakery-dining", family: "MaterialIcons" },
  { name: "brunch-dining", family: "MaterialIcons" },
  { name: "dinner-dining", family: "MaterialIcons" },
  { name: "lunch-dining", family: "MaterialIcons" },
  { name: "breakfast-dining", family: "MaterialIcons" },
  { name: "tapas", family: "MaterialIcons" },
  { name: "kebab-dining", family: "MaterialIcons" },
  { name: "icecream", family: "MaterialIcons" },
  { name: "cake", family: "MaterialIcons" },
  { name: "set-meal", family: "MaterialIcons" },
  { name: "bento", family: "MaterialIcons" },
  { name: "liquor", family: "MaterialIcons" },
  { name: "wine-bar", family: "MaterialIcons" },
  { name: "sports-bar", family: "MaterialIcons" },
  { name: "nightlife", family: "MaterialIcons" },
  { name: "local-drink", family: "MaterialIcons" },
  { name: "outdoor-grill", family: "MaterialIcons" },
  { name: "whatshot", family: "MaterialIcons" },
  { name: "ac-unit", family: "MaterialIcons" },
  { name: "shopping-basket", family: "MaterialIcons" },
  { name: "shopping-cart", family: "MaterialIcons" },
  { name: "store", family: "MaterialIcons" },
  { name: "storefront", family: "MaterialIcons" },
  { name: "scale", family: "MaterialIcons" },
  { name: "timer", family: "MaterialIcons" },
  { name: "egg", family: "MaterialIcons" },
  { name: "egg-alt", family: "MaterialIcons" },

  // Feather additions
  { name: "coffee", family: "Feather" },
  { name: "shopping-bag", family: "Feather" },
  { name: "shopping-cart", family: "Feather" },
  { name: "package", family: "Feather" },
  { name: "box", family: "Feather" },
  { name: "droplet", family: "Feather" },
  { name: "thermometer", family: "Feather" },
  { name: "clock", family: "Feather" },
  { name: "scissors", family: "Feather" },
  { name: "trash-2", family: "Feather" },
];

// Helper function to get icon family by name
export function getIconFamily(iconName: string): IconFamily {
  const icon = FOOD_ICONS.find((icon) => icon.name === iconName);

  if (icon?.name === "bacon") {
    console.log({ icon });
  }
  return icon?.family || "MaterialCommunityIcons";
}
