// Auto-categorization utility for pantry items

interface KeywordEntry {
  keyword: string;
  weight?: number; // Higher weight = stronger match (default: 1)
}

interface CategoryConfig {
  id: string;
  priority: number; // Higher = checked first (for tiebreakers)
  keywords: (string | KeywordEntry)[];
}

const CATEGORY_CONFIGS: CategoryConfig[] = [
  // Higher priority categories (more specific) first
  {
    id: "baby",
    priority: 100,
    keywords: [
      { keyword: "baby food", weight: 10 },
      { keyword: "baby formula", weight: 10 },
      { keyword: "infant formula", weight: 10 },
      "diaper",
      "diapers",
      "baby wipes",
      "pacifier",
      "sippy cup",
      "baby lotion",
      "baby powder",
      "baby shampoo",
      "baby cereal",
      "gerber",
      "similac",
      "enfamil",
      "huggies",
      "pampers",
    ],
  },
  {
    id: "pet",
    priority: 100,
    keywords: [
      { keyword: "dog food", weight: 10 },
      { keyword: "cat food", weight: 10 },
      { keyword: "pet food", weight: 10 },
      "dog treat",
      "cat treat",
      "pet treat",
      "cat litter",
      "kitty litter",
      "dog toy",
      "cat toy",
      "bird seed",
      "fish food",
      "pet shampoo",
      "flea",
      "tick collar",
      "purina",
      "pedigree",
      "meow mix",
      "iams",
      "blue buffalo",
      "kibble",
      "friskies",
      "fancy feast",
      "milk-bone",
    ],
  },
  {
    id: "health",
    priority: 95,
    keywords: [
      "vitamin",
      "supplement",
      "medicine",
      "medication",
      "bandage",
      "band-aid",
      "first aid",
      "aspirin",
      "ibuprofen",
      "tylenol",
      "advil",
      "acetaminophen",
      "cough syrup",
      "cold medicine",
      "allergy",
      "antihistamine",
      "benadryl",
      "zyrtec",
      "claritin",
      "antacid",
      "tums",
      "pepto",
      "laxative",
      "toothpaste",
      "toothbrush",
      "floss",
      "mouthwash",
      "listerine",
      "colgate",
      "shampoo",
      "conditioner",
      "body wash",
      "deodorant",
      "lotion",
      "sunscreen",
      "chapstick",
      "lip balm",
      "razor",
      "shaving cream",
      "cotton balls",
      "q-tips",
      "cotton swabs",
      "thermometer",
      "heating pad",
    ],
  },
  {
    id: "household",
    priority: 95,
    keywords: [
      { keyword: "paper towel", weight: 10 },
      { keyword: "toilet paper", weight: 10 },
      { keyword: "trash bag", weight: 10 },
      { keyword: "dish soap", weight: 10 },
      { keyword: "laundry detergent", weight: 10 },
      "detergent",
      "cleaner",
      "cleaning",
      "tissue",
      "tissues",
      "kleenex",
      "aluminum foil",
      "tin foil",
      "plastic wrap",
      "saran wrap",
      "cling wrap",
      "ziploc",
      "ziplock",
      "storage bag",
      "sandwich bag",
      "freezer bag",
      "bleach",
      "disinfectant",
      "lysol",
      "clorox",
      "windex",
      "sponge",
      "sponges",
      "scrubber",
      "dish soap",
      "dawn",
      "palmolive",
      "fabric softener",
      "dryer sheets",
      "bounce",
      "downy",
      "tide",
      "light bulb",
      "battery",
      "batteries",
      "duracell",
      "energizer",
      "broom",
      "mop",
      "dustpan",
      "vacuum bag",
      "air freshener",
      "febreze",
      "glade",
      "candle",
    ],
  },
  {
    id: "frozen",
    priority: 90,
    keywords: [
      { keyword: "frozen pizza", weight: 10 },
      { keyword: "frozen vegetable", weight: 10 },
      { keyword: "frozen fruit", weight: 10 },
      { keyword: "frozen dinner", weight: 10 },
      { keyword: "frozen meal", weight: 10 },
      { keyword: "ice cream", weight: 10 },
      { keyword: "frozen yogurt", weight: 8 },
      "frozen",
      "popsicle",
      "ice pop",
      "frozen waffle",
      "eggo",
      "frozen burrito",
      "hot pocket",
      "lean cuisine",
      "stouffer",
      "marie callender",
      "banquet",
      "birds eye",
      "ore-ida",
      "frozen fries",
      "frozen french fries",
      "tater tots",
      "frozen pie",
      "frozen pizza",
      "digiorno",
      "tombstone",
      "totino",
      "sorbet",
      "gelato",
      "frozen berries",
      "frozen corn",
    ],
  },
  {
    id: "deli",
    priority: 85,
    keywords: [
      { keyword: "lunch meat", weight: 10 },
      { keyword: "deli meat", weight: 10 },
      { keyword: "sliced turkey", weight: 10 },
      { keyword: "sliced ham", weight: 10 },
      { keyword: "sliced chicken", weight: 10 },
      "deli",
      "salami",
      "bologna",
      "pepperoni",
      "roast beef",
      "pastrami",
      "prosciutto",
      "mortadella",
      "capicola",
      "corned beef",
      "liverwurst",
      "oscar mayer",
      "boar's head",
      "hillshire",
      "buddig",
    ],
  },
  {
    id: "dairy",
    priority: 80,
    keywords: [
      { keyword: "cream cheese", weight: 10 },
      { keyword: "cottage cheese", weight: 10 },
      { keyword: "sour cream", weight: 10 },
      { keyword: "goat cheese", weight: 10 },
      { keyword: "shredded cheese", weight: 10 },
      { keyword: "string cheese", weight: 8 },
      { keyword: "cheese slice", weight: 8 },
      { keyword: "half and half", weight: 8 },
      { keyword: "heavy cream", weight: 8 },
      { keyword: "whipping cream", weight: 8 },
      "milk",
      "cheese",
      "butter",
      "cream",
      "yogurt",
      "greek yogurt",
      "mozzarella",
      "cheddar",
      "parmesan",
      "swiss",
      "provolone",
      "american cheese",
      "ricotta",
      "brie",
      "camembert",
      "gouda",
      "feta",
      "blue cheese",
      "monterey jack",
      "colby",
      "pepper jack",
      "havarti",
      "gruyere",
      "buttermilk",
      "whey",
      "kefir",
      "half & half",
      "creamer",
      "coffee creamer",
      "egg",
      "eggs",
      "egg white",
      "egg substitute",
      "kraft",
      "philadelphia",
      "chobani",
      "fage",
      "oikos",
      "yoplait",
      "dannon",
      "tillamook",
      "cabot",
      "sargento",
      "horizon",
      "organic valley",
    ],
  },
  {
    id: "meat",
    priority: 75,
    keywords: [
      { keyword: "chicken breast", weight: 10 },
      { keyword: "ground beef", weight: 10 },
      { keyword: "ground turkey", weight: 10 },
      { keyword: "pork chop", weight: 10 },
      { keyword: "beef steak", weight: 10 },
      { keyword: "chicken thigh", weight: 10 },
      { keyword: "chicken wing", weight: 10 },
      { keyword: "chicken drumstick", weight: 10 },
      { keyword: "pork loin", weight: 10 },
      { keyword: "pork tenderloin", weight: 10 },
      { keyword: "beef roast", weight: 10 },
      "chicken",
      "beef",
      "pork",
      "turkey",
      "lamb",
      "veal",
      "duck",
      "goose",
      "venison",
      "bison",
      "rabbit",
      "steak",
      "ribeye",
      "sirloin",
      "tenderloin",
      "filet mignon",
      "flank steak",
      "skirt steak",
      "t-bone",
      "porterhouse",
      "new york strip",
      "chuck roast",
      "brisket",
      "short rib",
      "bacon",
      "sausage",
      "bratwurst",
      "italian sausage",
      "breakfast sausage",
      "ham",
      "pork belly",
      "ribs",
      "baby back ribs",
      "spare ribs",
      "drumstick",
      "thigh",
      "wing",
      "whole chicken",
      "rotisserie",
      "ground pork",
      "meatball",
      "meatloaf",
      "fish",
      "salmon",
      "tuna",
      "cod",
      "tilapia",
      "mahi mahi",
      "halibut",
      "trout",
      "catfish",
      "bass",
      "snapper",
      "swordfish",
      "sardine",
      "anchovy",
      "shrimp",
      "prawn",
      "crab",
      "lobster",
      "scallop",
      "mussel",
      "clam",
      "oyster",
      "calamari",
      "squid",
      "octopus",
      "crawfish",
      "crayfish",
      "perdue",
      "tyson",
      "jennie-o",
      "butterball",
      "smithfield",
      "hormel",
    ],
  },
  {
    id: "produce",
    priority: 70,
    keywords: [
      // Fruits
      "apple",
      "apples",
      "banana",
      "bananas",
      "orange",
      "oranges",
      "clementine",
      "mandarin",
      "tangerine",
      "grapefruit",
      "lemon",
      "lemons",
      "lime",
      "limes",
      "grape",
      "grapes",
      "strawberry",
      "strawberries",
      "blueberry",
      "blueberries",
      "raspberry",
      "raspberries",
      "blackberry",
      "blackberries",
      "cranberry",
      "cherry",
      "cherries",
      "peach",
      "peaches",
      "nectarine",
      "plum",
      "plums",
      "apricot",
      "pear",
      "pears",
      "mango",
      "mangos",
      "mangoes",
      "papaya",
      "pineapple",
      "coconut",
      "kiwi",
      "pomegranate",
      "fig",
      "figs",
      "date",
      "dates",
      "watermelon",
      "cantaloupe",
      "honeydew",
      "melon",
      "avocado",
      "avocados",
      // Vegetables
      "tomato",
      "tomatoes",
      "cherry tomato",
      "grape tomato",
      "roma tomato",
      "potato",
      "potatoes",
      "sweet potato",
      "yam",
      "russet",
      "onion",
      "onions",
      "red onion",
      "yellow onion",
      "white onion",
      "green onion",
      "scallion",
      "shallot",
      "leek",
      "garlic",
      "ginger",
      "turmeric root",
      "lettuce",
      "romaine",
      "iceberg",
      "butter lettuce",
      "mixed greens",
      "spring mix",
      "spinach",
      "kale",
      "arugula",
      "chard",
      "collard greens",
      "mustard greens",
      "cabbage",
      "red cabbage",
      "napa cabbage",
      "bok choy",
      "brussels sprout",
      "broccoli",
      "broccolini",
      "cauliflower",
      "carrot",
      "carrots",
      "celery",
      "cucumber",
      "cucumbers",
      "bell pepper",
      "red pepper",
      "green pepper",
      "yellow pepper",
      "jalapeno",
      "serrano",
      "habanero",
      "poblano",
      "anaheim",
      "zucchini",
      "squash",
      "yellow squash",
      "butternut squash",
      "acorn squash",
      "spaghetti squash",
      "delicata",
      "eggplant",
      "artichoke",
      "mushroom",
      "mushrooms",
      "portobello",
      "cremini",
      "shiitake",
      "oyster mushroom",
      "corn on the cob",
      "corn cob",
      "asparagus",
      "green bean",
      "green beans",
      "snap pea",
      "snow pea",
      "peas",
      "edamame",
      "beet",
      "beets",
      "turnip",
      "radish",
      "radishes",
      "parsnip",
      "rutabaga",
      // Fresh herbs
      "cilantro",
      "parsley",
      "basil",
      "mint",
      "dill",
      "chives",
      "rosemary",
      "thyme",
      "oregano",
      "sage",
      "tarragon",
      // Brands
      "dole",
      "driscoll",
      "del monte",
      "chiquita",
      "earthbound",
    ],
  },
  {
    id: "bakery",
    priority: 65,
    keywords: [
      { keyword: "english muffin", weight: 10 },
      { keyword: "hamburger bun", weight: 10 },
      { keyword: "hot dog bun", weight: 10 },
      { keyword: "wheat bread", weight: 10 },
      { keyword: "white bread", weight: 10 },
      { keyword: "sourdough bread", weight: 10 },
      "bread",
      "loaf",
      "bagel",
      "bagels",
      "roll",
      "rolls",
      "dinner roll",
      "bun",
      "buns",
      "croissant",
      "muffin",
      "muffins",
      "donut",
      "doughnut",
      "donuts",
      "danish",
      "pastry",
      "baguette",
      "ciabatta",
      "focaccia",
      "pita",
      "pita bread",
      "naan",
      "flatbread",
      "tortilla",
      "tortillas",
      "flour tortilla",
      "corn tortilla",
      "wrap",
      "wraps",
      "rye bread",
      "pumpernickel",
      "brioche",
      "challah",
      "crouton",
      "croutons",
      "breadcrumb",
      "breadcrumbs",
      "panko",
      "thomas'",
      "sara lee",
      "pepperidge farm",
      "arnold",
      "dave's killer bread",
      "nature's own",
      "wonder bread",
      "martin's",
    ],
  },
  {
    id: "breakfast",
    priority: 60,
    keywords: [
      { keyword: "pancake mix", weight: 10 },
      { keyword: "waffle mix", weight: 10 },
      { keyword: "breakfast bar", weight: 10 },
      { keyword: "breakfast cereal", weight: 8 },
      "cereal",
      "oatmeal",
      "oats",
      "instant oatmeal",
      "steel cut oats",
      "rolled oats",
      "overnight oats",
      "granola",
      "muesli",
      "pancake",
      "waffle",
      "french toast",
      "pop tart",
      "pop-tart",
      "toaster strudel",
      "toaster pastry",
      "syrup",
      "maple syrup",
      "pancake syrup",
      "cheerios",
      "frosted flakes",
      "corn flakes",
      "special k",
      "raisin bran",
      "lucky charms",
      "cinnamon toast crunch",
      "froot loops",
      "fruit loops",
      "cocoa puffs",
      "cap'n crunch",
      "life cereal",
      "chex",
      "kix",
      "honey nut cheerios",
      "grape nuts",
      "shredded wheat",
      "quaker",
      "kellogg",
      "general mills",
      "post",
    ],
  },
  {
    id: "grains",
    priority: 55,
    keywords: [
      { keyword: "brown rice", weight: 10 },
      { keyword: "white rice", weight: 10 },
      { keyword: "jasmine rice", weight: 10 },
      { keyword: "basmati rice", weight: 10 },
      { keyword: "wild rice", weight: 10 },
      { keyword: "instant rice", weight: 10 },
      "rice",
      "quinoa",
      "couscous",
      "bulgur",
      "farro",
      "barley",
      "millet",
      "polenta",
      "grits",
      "cornmeal",
      "pasta",
      "spaghetti",
      "penne",
      "rigatoni",
      "fusilli",
      "rotini",
      "farfalle",
      "bowtie",
      "linguine",
      "fettuccine",
      "angel hair",
      "macaroni",
      "elbow",
      "lasagna",
      "ziti",
      "orzo",
      "shells",
      "egg noodle",
      "egg noodles",
      "ramen",
      "udon",
      "soba",
      "rice noodle",
      "lo mein",
      "chow mein",
      "barilla",
      "ronzoni",
      "de cecco",
      "buitoni",
      "uncle ben's",
      "minute rice",
      "near east",
      "rice-a-roni",
    ],
  },
  {
    id: "canned",
    priority: 50,
    keywords: [
      { keyword: "canned tomato", weight: 10 },
      { keyword: "canned bean", weight: 10 },
      { keyword: "canned tuna", weight: 10 },
      { keyword: "canned salmon", weight: 10 },
      { keyword: "canned chicken", weight: 10 },
      { keyword: "tomato sauce", weight: 10 },
      { keyword: "tomato paste", weight: 10 },
      { keyword: "crushed tomatoes", weight: 10 },
      { keyword: "diced tomatoes", weight: 10 },
      { keyword: "stewed tomatoes", weight: 10 },
      { keyword: "canned corn", weight: 10 },
      { keyword: "canned peas", weight: 10 },
      { keyword: "can of", weight: 8 },
      "canned",
      "beans",
      "black beans",
      "kidney beans",
      "pinto beans",
      "cannellini",
      "navy beans",
      "great northern",
      "refried beans",
      "chickpeas",
      "garbanzo",
      "lentils",
      "soup",
      "chicken soup",
      "tomato soup",
      "vegetable soup",
      "broth",
      "stock",
      "chicken broth",
      "beef broth",
      "vegetable broth",
      "bouillon",
      "olives",
      "pickles",
      "pickle",
      "sauerkraut",
      "artichoke hearts",
      "roasted red pepper",
      "hearts of palm",
      "bamboo shoots",
      "water chestnut",
      "coconut milk",
      "evaporated milk",
      "condensed milk",
      "sweetened condensed",
      "spam",
      "corned beef hash",
      "campbell's",
      "progresso",
      "swanson",
      "goya",
      "bush's",
      "del monte",
      "hunt's",
      "contadina",
      "muir glen",
      "rotel",
      "starkist",
      "bumble bee",
    ],
  },
  {
    id: "condiments",
    priority: 45,
    keywords: [
      { keyword: "hot sauce", weight: 10 },
      { keyword: "soy sauce", weight: 10 },
      { keyword: "bbq sauce", weight: 10 },
      { keyword: "teriyaki sauce", weight: 10 },
      { keyword: "steak sauce", weight: 10 },
      { keyword: "fish sauce", weight: 10 },
      { keyword: "oyster sauce", weight: 10 },
      { keyword: "hoisin sauce", weight: 10 },
      { keyword: "buffalo sauce", weight: 10 },
      { keyword: "wing sauce", weight: 10 },
      { keyword: "pasta sauce", weight: 10 },
      { keyword: "marinara sauce", weight: 10 },
      { keyword: "alfredo sauce", weight: 10 },
      { keyword: "pizza sauce", weight: 10 },
      { keyword: "salad dressing", weight: 10 },
      "ketchup",
      "catsup",
      "mustard",
      "dijon",
      "yellow mustard",
      "spicy mustard",
      "mayo",
      "mayonnaise",
      "miracle whip",
      "relish",
      "pickle relish",
      "sweet relish",
      "salsa",
      "pico de gallo",
      "hot salsa",
      "mild salsa",
      "guacamole",
      "hummus",
      "worcestershire",
      "a1",
      "a-1",
      "sriracha",
      "tabasco",
      "frank's red hot",
      "cholula",
      "tapatio",
      "valentina",
      "ranch",
      "blue cheese dressing",
      "caesar dressing",
      "italian dressing",
      "vinaigrette",
      "thousand island",
      "honey mustard dressing",
      "marinade",
      "teriyaki",
      "bbq",
      "barbecue",
      "tartar sauce",
      "cocktail sauce",
      "horseradish",
      "pesto",
      "tapenade",
      "chutney",
      "aioli",
      "remoulade",
      "heinz",
      "french's",
      "hellmann's",
      "best foods",
      "kraft",
      "hidden valley",
      "ken's",
      "wishbone",
      "newman's own",
      "prego",
      "ragu",
      "bertolli",
      "classico",
    ],
  },
  {
    id: "spices",
    priority: 45,
    keywords: [
      { keyword: "garlic powder", weight: 10 },
      { keyword: "onion powder", weight: 10 },
      { keyword: "chili powder", weight: 10 },
      { keyword: "curry powder", weight: 10 },
      { keyword: "black pepper", weight: 10 },
      { keyword: "white pepper", weight: 10 },
      { keyword: "cayenne pepper", weight: 10 },
      { keyword: "red pepper flakes", weight: 10 },
      { keyword: "italian seasoning", weight: 10 },
      { keyword: "taco seasoning", weight: 10 },
      { keyword: "cajun seasoning", weight: 10 },
      { keyword: "old bay", weight: 10 },
      { keyword: "lemon pepper", weight: 10 },
      { keyword: "seasoned salt", weight: 10 },
      { keyword: "celery salt", weight: 10 },
      { keyword: "garlic salt", weight: 10 },
      "spice",
      "seasoning",
      "cinnamon",
      "paprika",
      "smoked paprika",
      "cumin",
      "coriander",
      "turmeric",
      "ginger powder",
      "nutmeg",
      "allspice",
      "clove",
      "cloves",
      "cardamom",
      "star anise",
      "bay leaf",
      "bay leaves",
      "oregano",
      "thyme",
      "rosemary",
      "sage",
      "basil",
      "dill",
      "tarragon",
      "marjoram",
      "fennel seed",
      "mustard seed",
      "celery seed",
      "poppy seed",
      "sesame seed",
      "caraway",
      "cumin seed",
      "coriander seed",
      "vanilla",
      "vanilla extract",
      "almond extract",
      "peppermint extract",
      "saffron",
      "sumac",
      "za'atar",
      "garam masala",
      "five spice",
      "herbs de provence",
      "bouquet garni",
      "salt",
      "sea salt",
      "kosher salt",
      "himalayan salt",
      "table salt",
      "pepper",
      "peppercorn",
      "ground pepper",
      "msg",
      "accent",
      "mccormick",
      "spice islands",
      "morton",
      "lawry's",
      "tone's",
    ],
  },
  {
    id: "baking",
    priority: 40,
    keywords: [
      { keyword: "baking soda", weight: 10 },
      { keyword: "baking powder", weight: 10 },
      { keyword: "chocolate chips", weight: 10 },
      { keyword: "cake mix", weight: 10 },
      { keyword: "brownie mix", weight: 10 },
      { keyword: "cookie mix", weight: 10 },
      { keyword: "muffin mix", weight: 10 },
      { keyword: "brown sugar", weight: 10 },
      { keyword: "powdered sugar", weight: 10 },
      { keyword: "confectioner's sugar", weight: 10 },
      { keyword: "all purpose flour", weight: 10 },
      { keyword: "bread flour", weight: 10 },
      { keyword: "cake flour", weight: 10 },
      { keyword: "whole wheat flour", weight: 10 },
      { keyword: "cocoa powder", weight: 10 },
      "flour",
      "sugar",
      "yeast",
      "active dry yeast",
      "instant yeast",
      "cornstarch",
      "corn starch",
      "arrowroot",
      "tapioca starch",
      "almond flour",
      "coconut flour",
      "gluten free flour",
      "shortening",
      "crisco",
      "lard",
      "baking chocolate",
      "unsweetened chocolate",
      "semi-sweet",
      "dark chocolate",
      "white chocolate chips",
      "butterscotch chips",
      "peanut butter chips",
      "frosting",
      "icing",
      "fondant",
      "sprinkles",
      "food coloring",
      "pie crust",
      "phyllo",
      "puff pastry",
      "graham cracker crust",
      "gelatin",
      "knox",
      "pectin",
      "sure-jell",
      "cream of tartar",
      "meringue powder",
      "sweetened condensed milk",
      "molasses",
      "corn syrup",
      "honey",
      "duncan hines",
      "betty crocker",
      "pillsbury",
      "gold medal",
      "king arthur",
      "ghirardelli",
      "baker's",
      "nestle toll house",
    ],
  },
  {
    id: "pantry",
    priority: 35,
    keywords: [
      { keyword: "olive oil", weight: 10 },
      { keyword: "vegetable oil", weight: 10 },
      { keyword: "canola oil", weight: 10 },
      { keyword: "coconut oil", weight: 10 },
      { keyword: "sesame oil", weight: 10 },
      { keyword: "avocado oil", weight: 10 },
      { keyword: "peanut butter", weight: 10 },
      { keyword: "almond butter", weight: 10 },
      { keyword: "maple syrup", weight: 10 },
      { keyword: "apple cider vinegar", weight: 10 },
      { keyword: "balsamic vinegar", weight: 10 },
      { keyword: "red wine vinegar", weight: 10 },
      { keyword: "white wine vinegar", weight: 10 },
      { keyword: "rice vinegar", weight: 10 },
      "oil",
      "cooking oil",
      "spray oil",
      "cooking spray",
      "pam",
      "vinegar",
      "white vinegar",
      "distilled vinegar",
      "honey",
      "agave",
      "stevia",
      "splenda",
      "sugar substitute",
      "syrup",
      "jam",
      "jelly",
      "preserves",
      "marmalade",
      "fruit spread",
      "nutella",
      "chocolate spread",
      "nut butter",
      "sunflower butter",
      "tahini",
      "peanuts",
      "almonds",
      "walnuts",
      "cashews",
      "pecans",
      "pistachios",
      "mixed nuts",
      "trail mix",
      "sunflower seeds",
      "pumpkin seeds",
      "dried fruit",
      "raisins",
      "craisins",
      "dried cranberries",
      "dried apricots",
      "dates",
      "prunes",
      "dried mango",
      "jif",
      "skippy",
      "peter pan",
      "smucker's",
      "welch's",
    ],
  },
  {
    id: "snacks",
    priority: 30,
    keywords: [
      { keyword: "potato chips", weight: 10 },
      { keyword: "tortilla chips", weight: 10 },
      { keyword: "corn chips", weight: 10 },
      { keyword: "granola bar", weight: 10 },
      { keyword: "protein bar", weight: 10 },
      { keyword: "energy bar", weight: 10 },
      { keyword: "fruit snacks", weight: 10 },
      { keyword: "cheese puffs", weight: 10 },
      { keyword: "cheese crackers", weight: 10 },
      { keyword: "graham crackers", weight: 10 },
      { keyword: "animal crackers", weight: 10 },
      "chips",
      "crackers",
      "cracker",
      "pretzels",
      "pretzel",
      "popcorn",
      "microwave popcorn",
      "kettle corn",
      "cookies",
      "biscuit",
      "biscuits",
      "wafer",
      "wafers",
      "candy",
      "chocolate",
      "chocolate bar",
      "candy bar",
      "gummy",
      "gummies",
      "gummy bears",
      "sour candy",
      "licorice",
      "m&m",
      "snickers",
      "reese's",
      "kit kat",
      "twix",
      "hershey",
      "skittles",
      "starburst",
      "jolly rancher",
      "haribo",
      "nuts",
      "trail mix",
      "beef jerky",
      "jerky",
      "slim jim",
      "goldfish",
      "cheez-it",
      "cheez it",
      "wheat thins",
      "triscuit",
      "ritz",
      "lays",
      "doritos",
      "cheetos",
      "pringles",
      "fritos",
      "tostitos",
      "sun chips",
      "kind bar",
      "nature valley",
      "clif bar",
      "larabar",
      "rxbar",
      "oreo",
      "chips ahoy",
      "nutter butter",
      "fig newton",
      "nilla wafer",
      "rice krispies treats",
      "little debbie",
      "hostess",
      "fruit roll up",
      "gushers",
      "welch's fruit snacks",
      "pudding",
      "jello",
      "jell-o",
    ],
  },
  {
    id: "beverages",
    priority: 25,
    keywords: [
      { keyword: "orange juice", weight: 10 },
      { keyword: "apple juice", weight: 10 },
      { keyword: "grape juice", weight: 10 },
      { keyword: "cranberry juice", weight: 10 },
      { keyword: "tomato juice", weight: 10 },
      { keyword: "vegetable juice", weight: 10 },
      { keyword: "sparkling water", weight: 10 },
      { keyword: "mineral water", weight: 10 },
      { keyword: "coconut water", weight: 10 },
      { keyword: "energy drink", weight: 10 },
      { keyword: "sports drink", weight: 10 },
      { keyword: "iced tea", weight: 10 },
      { keyword: "sweet tea", weight: 10 },
      { keyword: "green tea", weight: 10 },
      { keyword: "black tea", weight: 10 },
      { keyword: "herbal tea", weight: 10 },
      { keyword: "k-cup", weight: 10 },
      { keyword: "k cup", weight: 10 },
      "water",
      "bottled water",
      "spring water",
      "distilled water",
      "juice",
      "lemonade",
      "limeade",
      "fruit punch",
      "kool-aid",
      "kool aid",
      "soda",
      "pop",
      "cola",
      "coke",
      "coca-cola",
      "pepsi",
      "sprite",
      "7-up",
      "7up",
      "dr pepper",
      "mountain dew",
      "fanta",
      "root beer",
      "ginger ale",
      "diet soda",
      "diet coke",
      "coke zero",
      "pepsi zero",
      "la croix",
      "lacroix",
      "perrier",
      "topo chico",
      "san pellegrino",
      "gatorade",
      "powerade",
      "body armor",
      "propel",
      "red bull",
      "monster",
      "rockstar",
      "bang",
      "coffee",
      "ground coffee",
      "coffee beans",
      "instant coffee",
      "decaf",
      "tea",
      "tea bags",
      "loose leaf tea",
      "hot chocolate",
      "cocoa mix",
      "swiss miss",
      "kombucha",
      "gt's",
      "health-ade",
      "almond milk",
      "oat milk",
      "soy milk",
      "coconut milk",
      "plant milk",
      "silk",
      "oatly",
      "califia",
      "starbucks",
      "dunkin",
      "folgers",
      "maxwell house",
      "nescafe",
      "lipton",
      "celestial seasonings",
      "tazo",
      "twinings",
      "bigelow",
      "tropicana",
      "simply orange",
      "minute maid",
      "ocean spray",
      "v8",
      "nesquik",
      "ovaltine",
      "beer",
      "wine",
      "hard seltzer",
      "white claw",
      "truly",
      "vodka",
      "rum",
      "whiskey",
      "tequila",
      "gin",
    ],
  },
];

/**
 * Normalize a string for matching
 */
function normalize(str: string): string {
  return str.toLowerCase().trim().replace(/['']/g, "'");
}

/**
 * Check if the item name contains the keyword as a whole word or phrase
 */
function matchesKeyword(itemName: string, keyword: string): boolean {
  const normalizedItem = normalize(itemName);
  const normalizedKeyword = normalize(keyword);

  // Exact match
  if (normalizedItem === normalizedKeyword) {
    return true;
  }

  // Check for word boundary match (not partial word)
  // This prevents "corn" from matching "popcorn"
  const regex = new RegExp(
    `(^|\\s|-)${escapeRegex(normalizedKeyword)}(s|es)?($|\\s|-)`,
    "i"
  );
  return regex.test(normalizedItem);
}

/**
 * Escape special regex characters
 */
function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Get the weight for a keyword entry
 */
function getWeight(entry: string | KeywordEntry): number {
  if (typeof entry === "string") {
    return 1;
  }
  return entry.weight || 1;
}

/**
 * Get the keyword string from an entry
 */
function getKeyword(entry: string | KeywordEntry): string {
  if (typeof entry === "string") {
    return entry;
  }
  return entry.keyword;
}

interface CategoryScore {
  id: string;
  score: number;
  priority: number;
}

/**
 * Calculate match score for an item against a category
 */
function calculateCategoryScore(
  itemName: string,
  config: CategoryConfig
): CategoryScore {
  let score = 0;
  const normalizedItem = normalize(itemName);

  for (const entry of config.keywords) {
    const keyword = getKeyword(entry);
    const weight = getWeight(entry);

    if (matchesKeyword(normalizedItem, keyword)) {
      // Longer keyword matches are more specific, so they get bonus points
      const lengthBonus = keyword.split(" ").length;

      // Exact match gets big bonus
      if (normalizedItem === normalize(keyword)) {
        score += weight * 10 * lengthBonus;
      } else {
        score += weight * lengthBonus;
      }
    }
  }

  return {
    id: config.id,
    score,
    priority: config.priority,
  };
}

/**
 * Automatically categorizes an item based on its name
 * @param itemName - The name of the item to categorize
 * @returns The category ID that best matches the item, or 'other' if no match found
 */
export function autoCategorizeItem(itemName: string): string {
  if (!itemName.trim()) {
    return "other";
  }

  const scores = CATEGORY_CONFIGS.map((config) =>
    calculateCategoryScore(itemName, config)
  )
    .filter((score) => score.score > 0)
    .sort((a, b) => {
      // Sort by score first, then by priority as tiebreaker
      if (b.score !== a.score) {
        return b.score - a.score;
      }
      return b.priority - a.priority;
    });

  return scores.length > 0 ? scores[0].id : "other";
}

/**
 * Gets suggested categories for an item (top 3 matches)
 * @param itemName - The name of the item
 * @returns Array of category IDs sorted by relevance
 */
export function getSuggestedCategories(itemName: string): string[] {
  if (!itemName.trim()) {
    return [];
  }

  const scores = CATEGORY_CONFIGS.map((config) =>
    calculateCategoryScore(itemName, config)
  )
    .filter((score) => score.score > 0)
    .sort((a, b) => {
      if (b.score !== a.score) {
        return b.score - a.score;
      }
      return b.priority - a.priority;
    });

  return scores.slice(0, 3).map((score) => score.id);
}

/**
 * Debug function to see all matching scores for an item
 */
export function debugCategorization(itemName: string): CategoryScore[] {
  return CATEGORY_CONFIGS
    .map(config => calculateCategoryScore(itemName, config))
    .filter(score => score.score > 0)
    .sort((a, b) => b.score - a.score);
}
